name: Build and Test Project

on:
  workflow_call:

jobs:
  build-mock-maker-default-member-accessor-default:
    uses: ellaella12/mockito/.github/workflows/build.yml@feature/build-once-test-all
    with:
      mock-maker: 'mock-maker-default'
      member-accessor: 'member-accessor-default'
  #
  #  build-mock-maker-inline-member-accessor-module:
  #    uses: mockito/mockito/.github/workflows/build.yml@feature/build-once-test-all
  #    with:
  #      mock-maker: 'mock-maker-inline'
  #      member-accessor: 'member-accessor-module'
  #
  #  build-mock-maker-subclass-member-accessor-module:
  #    uses: mockito/mockito/.github/workflows/build.yml@feature/build-once-test-all
  #    with:
  #      mock-maker: 'mock-maker-subclass'
  #      member-accessor: 'member-accessor-module'
  #
  #  build-mock-maker-subclass-member-accessor-reflection:
  #    uses: mockito/mockito/.github/workflows/build.yml@feature/build-once-test-all
  #    with:
  #      mock-maker: 'mock-maker-subclass'
  #      member-accessor: 'member-accessor-reflection'
  #
  #  build-mock-maker-inline-member-accessor-reflection:
  #    uses: mockito/mockito/.github/workflows/build.yml@feature/build-once-test-all
  #    with:
  #      mock-maker: 'mock-maker-inline'
  #      member-accessor: 'member-accessor-reflection'
